sensors: 
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /red/camera/depth_registered/points
    max_range: 100.0
    frame_subsample: 1
    point_subsample: 1
